# Generated by Django 4.0 on 2022-01-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
