# Generated by Django 4.0 on 2022-01-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_feed_contact_alter_feed_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Type',
            new_name='Feed_Type',
        ),
    ]
